version: 0.2

phases:
  pre_build:
    commands:
      - git config --global user.name "Yinon Hever"
      - git config --global user.email "yinonehever@gmail.com"
      - git pull origin main
  build:
    commands:
      - npm install
      - npm run build
