version: 0.2

phases:
  pre_build:
    commands:
      - git config --global user.name "Yinon Hever"
      - git config --global user.email "yinonehever@gmail.com"
      - pwd
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - ls
      - git init
      - git status
      - git remote -v
      - git branch -a
      - git remote add origin https://github.com/yinonhever/domain-checker
      - git fetch origin main
      - git merge origin/main
      - git pull origin main
  build:
    commands:
      - npm install
      - npm run build
