version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  pre_build:
    commands:
      - git init
      - git remote add origin https://github.com/yinonhever/domain-checker
      - git fetch origin main
      - git reset --hard origin/main
  build:
    commands:
      - npm install
      - npm run build
  artifacts:
    files:
      - "**/*"
    base-directory: /
    name: domain-checker-backend
    discard-paths: no
