version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
